image: php:7.2-fpm

stages:
  - test
  - build
  - deploy

before_script:
  - apt-get update && apt-get install -y --no-install-recommends apt-utils
  - apt-get install -y curl gnupg2 unzip openssh-client
  - curl -sS https://getcomposer.org/installer -o composer-setup.php
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh && bash nodesource_setup.sh
  - apt-get install -y nodejs
  - npm install -g yarn
  - php -v
  - node -v
  - npm -v
  - pwd
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - touch ~/.ssh/id_rsa && echo $SSH_PRIVATE_KEY >> ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - chmod 700 ~/.ssh
  - ssh-keyscan 68.183.75.44 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - npm config set scripts-prepend-node-path true
  - cd ~/.ssh && ls -al
  - cd /builds/AndrewKiri/reactday

staging build:
  stage: deploy
  script:
    - composer install
    - yarn install
    - yarn build
    - vendor/bin/dep deploy staging
  environment:
    name: staging
    url: https://staging.reactday.pl
  only:
    - staging

production build:
  stage: deploy
  script:
    - composer install
    - yarn install
    - yarn build
    - vendor/bin/dep deploy production
  environment:
    name: production
    url: https://reactday.pl
  only:
    - master
